[[NVPTX_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16aa78ddb47ac9ce683870846b0de6fcfcb51ea0"
libc = "glibc"
os = "linux"

    [[NVPTX_LLVM_Backend.download]]
    sha256 = "9efad17df5bd66c874bbeddeb250e51d03119dee757da9aeb86c6d239a996515"
    url = "https://github.com/JuliaBinaryWrappers/NVPTX_LLVM_Backend_jll.jl/releases/download/NVPTX_LLVM_Backend-v23.1.1+1/NVPTX_LLVM_Backend.v23.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[NVPTX_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eb2be45a6ab6166cf5f9ee8611404da9d49920c"
libc = "glibc"
os = "linux"

    [[NVPTX_LLVM_Backend.download]]
    sha256 = "0bd66443dc94e0aeec30b4137bffb24775fae11fde7c94ed9c35d98708ced19d"
    url = "https://github.com/JuliaBinaryWrappers/NVPTX_LLVM_Backend_jll.jl/releases/download/NVPTX_LLVM_Backend-v23.1.1+1/NVPTX_LLVM_Backend.v23.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[NVPTX_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a087e3d92992c43c16b0213c8cae5fcac80eb685"
os = "windows"

    [[NVPTX_LLVM_Backend.download]]
    sha256 = "a81f0c14c57400b84116c5fb153328f994424353377a6c1945543f8b548a3a26"
    url = "https://github.com/JuliaBinaryWrappers/NVPTX_LLVM_Backend_jll.jl/releases/download/NVPTX_LLVM_Backend-v23.1.1+1/NVPTX_LLVM_Backend.v23.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
