[[NVPTX_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89edf5e7f2e736345cd5def6fa01bc73462bc539"
libc = "glibc"
os = "linux"

    [[NVPTX_LLVM_Backend.download]]
    sha256 = "06e2e278b03ead9fa5d7bab67d50a12422aedfc95d04fc0fff91f1887217c186"
    url = "https://github.com/JuliaBinaryWrappers/NVPTX_LLVM_Backend_jll.jl/releases/download/NVPTX_LLVM_Backend-v23.1.1+0/NVPTX_LLVM_Backend.v23.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[NVPTX_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6375a606aacd4f142b2dcebf13fa0c4763eb2c45"
libc = "glibc"
os = "linux"

    [[NVPTX_LLVM_Backend.download]]
    sha256 = "4c919f3a15130f3d639d8d9e9723c6b974ea76046c6d51e29be827023b43f260"
    url = "https://github.com/JuliaBinaryWrappers/NVPTX_LLVM_Backend_jll.jl/releases/download/NVPTX_LLVM_Backend-v23.1.1+0/NVPTX_LLVM_Backend.v23.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[NVPTX_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0f3f2b478e7c1f3a97887c3f14a67df42aa496c"
os = "windows"

    [[NVPTX_LLVM_Backend.download]]
    sha256 = "4eeb1d3f3cb884e9456f0604c149aa560c1a2ac695d120ec5f7dbf625cde346f"
    url = "https://github.com/JuliaBinaryWrappers/NVPTX_LLVM_Backend_jll.jl/releases/download/NVPTX_LLVM_Backend-v23.1.1+0/NVPTX_LLVM_Backend.v23.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
