# Autogenerated wrapper script for NVPTX_LLVM_Backend_jll for aarch64-linux-gnu-cxx11
export libnvptx

using Zlib_jll
JLLWrappers.@generate_wrapper_header("NVPTX_LLVM_Backend")
JLLWrappers.@declare_library_product(libnvptx, "libnvptx.so")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libnvptx,
        "lib/libnvptx.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
